### ISSUE TITLE
a few skirt patterns have unexpected panels.

### ISSUE THREAD

**Issue by whatyougonnado** [maria-korosteleva/GarmentCode#1]
[Logs.zip](https://github.com/maria-korosteleva/GarmentCode/files/13669432/Logs.zip)
I make skirt patterns using garment code GUI, but when I ran with SkirtCircle or SkirtManyPanels, there were some problems.

1) SkirtCircle back panel normal is reversed at qualoth, maya2022.
2) SkirtManyPanels panels are not working at qualoth, maya2022.

![image](https://github.com/maria-korosteleva/GarmentCode/assets/21278478/8e23ccba-8ad8-4527-8e8b-c04785a3de83)
![image](https://github.com/maria-korosteleva/GarmentCode/assets/21278478/69cc8acc-10f6-43f8-8b07-169cd930298c)

**Comment by maria-korosteleva** [comment]
Hi! Thank you for reporting!

1) I faced this issue with Qualoth, especially for the circular panels. The orientation of the edges in the panels defines the normal correctly, but Qualoth then interprets it the wrong way. It's a bug somewhere there =)

2) Could you check the outputs in the Script Editor, and share it here? It might contain additional information and error messages

**Comment by maria-korosteleva** [comment]
@whatyougonnado I have found an answer to your question #2. The pattern itself is valid -- it seems that Qualoth fails to create a mesh when the panel has very sharp angles. E.g. in SkirtPanels case when the bottom of the panel is much wider than the top, the bottom angles become very sharp). 

If you need this particular design, I'd suggest trying to increase the mesh resolution for Qualoth simulation. Otherwise, reduce the skirt bottom width ('suns' parameter) to make the angles less sharp.

**Comment by whatyougonnado** [comment]
Thank you, I'll try the last solution!
