### ISSUE TITLE
Can't render garment properly

### ISSUE THREAD

**Issue by machffud** [maria-korosteleva/GarmentCode#18]
Hi Maria,

Thank you for your amazing work and for making it open-source!

While testing some renders, I occasionally encounter a result like the one shown below, where the garment consistently appears around the feet. Could you help me understand what might be causing this issue?

<img width="454" alt="image" src="https://github.com/user-attachments/assets/0530926a-8d4b-4654-a193-7e0b3bc1c70f">

Additionally, my objective is to utilize the 3D rendering feature of Nvidia-Warp that you created by using my own specification.json as input. I am aware that the format of my specification.json differs slightly from yours, and I have attempted to adjust it, but I keep getting the same rendering result as shown above.

Here are a few things I'd like to clarify:

1. Is specification.json sufficient as the sole input for Nvidia-Warp 3D rendering? (I am using the same default body as you.)
2. What are the essential fields in your specification.json? Even when I tried modifying fields like panel_name, label_body, label_endpoints, and type_curvature, the rendered output remained the same.

Thank you for your help!

**Comment by maria-korosteleva** [comment]
Hi! Thank you for your kind words =)

Please, attach the design parameter file and a JSON file so that I can
reproduce the problem. That's definitely not rendering, the garment is
falling down during the simulation. It could be an alignment problem or
just a problematic design

Also, please create a new GitHub issue for your second question to separate
the issues by topic =)

вт, 8 окт. 2024 г. в 09:21, machffud ***@***.***>:

**Comment by machffud** [comment]
Thanks for fast response!

Here are my JSON and design parameter files (this is a different sample where the garment appears to fall).

[rand_L575B2COTH.zip](https://github.com/user-attachments/files/17289657/rand_L575B2COTH.zip)

I’ve also noticed that I can successfully render 3D without using the design_params.yaml file. I verified this by replacing the specification.json in rand_y with the one from rand_x (which rendered successfully), and then deleting the design_params.yaml in rand_y.

**Comment by yukistavailable** [comment]
Hi @machffud 
I've simulated your specification.json
I think you need to add an upper garment and waistband to avoid the pants slide
![test_sim](https://github.com/user-attachments/assets/75a62f0b-1492-4883-835f-1a4f2b66da76)

**Comment by machffud** [comment]
> Hi @machffud I've simulated your specification.json I think you need to add an upper garment and waistband to avoid the pants slide ![test_sim](https://private-user-images.githubusercontent.com/51744925/374526420-75a62f0b-1492-4883-835f-1a4f2b66da76.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MjYyODYsIm5iZiI6MTcyODQyNTk4NiwicGF0aCI6Ii81MTc0NDkyNS8zNzQ1MjY0MjAtNzVhNjJmMGItMTQ5Mi00ODgzLTgzNWYtMWE0ZjJiNjZkYTc2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDIyMTk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MzAzNjc4ZjE5YWE4ZWM1OWNkMTBkODdmNDZiMjNhM2Q2ZGIzOWM3Y2VkM2RjOWM2YmJlYTdjMDZhNzA2NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YhsvYtzlf9lIEUYjqyLHT-D7kYLD4FF0UJny2wl6LwM) [ ![test_sim](https://private-user-images.githubusercontent.com/51744925/374526420-75a62f0b-1492-4883-835f-1a4f2b66da76.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MjYyODYsIm5iZiI6MTcyODQyNTk4NiwicGF0aCI6Ii81MTc0NDkyNS8zNzQ1MjY0MjAtNzVhNjJmMGItMTQ5Mi00ODgzLTgzNWYtMWE0ZjJiNjZkYTc2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDIyMTk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MzAzNjc4ZjE5YWE4ZWM1OWNkMTBkODdmNDZiMjNhM2Q2ZGIzOWM3Y2VkM2RjOWM2YmJlYTdjMDZhNzA2NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YhsvYtzlf9lIEUYjqyLHT-D7kYLD4FF0UJny2wl6LwM) ](https://private-user-images.githubusercontent.com/51744925/374526420-75a62f0b-1492-4883-835f-1a4f2b66da76.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MjYyODYsIm5iZiI6MTcyODQyNTk4NiwicGF0aCI6Ii81MTc0NDkyNS8zNzQ1MjY0MjAtNzVhNjJmMGItMTQ5Mi00ODgzLTgzNWYtMWE0ZjJiNjZkYTc2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDIyMTk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MzAzNjc4ZjE5YWE4ZWM1OWNkMTBkODdmNDZiMjNhM2Q2ZGIzOWM3Y2VkM2RjOWM2YmJlYTdjMDZhNzA2NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YhsvYtzlf9lIEUYjqyLHT-D7kYLD4FF0UJny2wl6LwM) [ ](https://private-user-images.githubusercontent.com/51744925/374526420-75a62f0b-1492-4883-835f-1a4f2b66da76.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0MjYyODYsIm5iZiI6MTcyODQyNTk4NiwicGF0aCI6Ii81MTc0NDkyNS8zNzQ1MjY0MjAtNzVhNjJmMGItMTQ5Mi00ODgzLTgzNWYtMWE0ZjJiNjZkYTc2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDIyMTk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1MzAzNjc4ZjE5YWE4ZWM1OWNkMTBkODdmNDZiMjNhM2Q2ZGIzOWM3Y2VkM2RjOWM2YmJlYTdjMDZhNzA2NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YhsvYtzlf9lIEUYjqyLHT-D7kYLD4FF0UJny2wl6LwM)

Hi @yukistavailable,
Since I'm a newbie in this field, could you tell me which part and what kind of things I should add to the specifications?
FYI, I am also experiencing the same issue with upper garments, so I can learn the patterns.
Thanks.

**Comment by yukistavailable** [comment]
Hi @machffud,
You can use this json file and see the simulated result 
[rand_L575B2COTH.json](https://github.com/user-attachments/files/17306584/rand_L575B2COTH.json)

This includes an upper garment and works well

**Comment by maria-korosteleva** [comment]
As @yukistavailable correctly pointed out, your pant example slides down because they are slightly too big, too heavy or a combination of both. This may happen for some design parameters, and it's normal -- likely, this design would not be wearable in real life as well. One known problem here is that XPBD simulation tends to produce stretchy materials despite the high values for stiffness parameter. Due to this bias, sometimes even theoretically correctly fitted garments may slide down when the bottom part is heavy (has a lot of fabric) and there is too little area that is hugging the body to hold all the fabric in place. 

For similar reasons, sliding can happen on the upper garment as well -- when the neck opening is too wide or too deep, and the rest of the garment is heavy. 

The parameters to be adjusted to fix the garment in place would be different for each individual design, and there are likely to be many different solutions. Try to use the above considerations and experiment with different parameters to either reduce the amount of loose fabric used (e.g. reduce the width of waistband in your pant example) or to add more support in the area that holds the garment on the body (make sure the raise of the pants is 1. or closer to 1.). 

To get the intermediate simulation results as @yukistavailable showed here, you can run the simulation with the script instead of GUI and enable storing the USD on this line: https://github.com/maria-korosteleva/GarmentCode/blob/3ebf48c840d629a039f235d79e236df7df9d9142/test_garment_sim.py#L69 
The simulation result will then contain the `.usd` file with all the simulation frames, which can be viewed, for example, in blender

**Comment by machffud** [comment]
Thanks for your help ! @maria-korosteleva @yukistavailable
