### ISSUE TITLE
T-posed body?

### ISSUE THREAD

**Issue by yukistavailable** [maria-korosteleva/GarmentCode#20]
Hi authors, 
Thank you for your outstanding work! I'm excited about this comprehensive pipeline for generating garment datasets.

I would like to use a t-posed body for rendering and attempted to use my own t-posed SMPL body. 
However, I encountered an issue due to the absence of the corresponding segmentation JSON file.
Would it be possible for you to provide a t-posed version of the "mean_all" body model? 
Your assistance would be greatly appreciated.

Thank you for your time and help!

**Comment by yukistavailable** [comment]
I made the t-posed version
".txt" should be replaced with ".obj" when used
[mean_all_t_pose.txt](https://github.com/user-attachments/files/17306637/mean_all_t_pose.txt)

**Comment by maria-korosteleva** [comment]
Hi @yukistavailable 
Thank you for your kind words and for sharing a model in t-pose! 

It would be great if you could add it to the set of our basic body models here: https://github.com/maria-korosteleva/GarmentCode/tree/main/assets/bodies and set up a pull request so that it's added to the repo directly =) 

Also, if you do need to use SMPL body model, the segmentation file does exist, [here](https://github.com/maria-korosteleva/GarmentCode/blob/main/assets/bodies/smpl_vert_segmentation.json). But to use it you simply need to flip the smpl flag in the path config, e.g., here: https://github.com/maria-korosteleva/GarmentCode/blob/3ebf48c840d629a039f235d79e236df7df9d9142/test_garment_sim.py#L49

**Comment by NagabhushanSN24** [comment]
@yukistavailable can you please explain how you created the T-pose body? I mean, if I select any random body mesh from 5000_body_shapes_and_measures, how can I change it to T-pose?
