### ISSUE TITLE
Using external pattern without design_params.yaml

### ISSUE THREAD

**Issue by TanJinxia** [maria-korosteleva/GarmentCode#26]
Dear @maria-korosteleva ,When I run the command 

> python pattern_data_sim.py --data /share/tjx/sewformer/Sewformer/outputs/deepfashion/Detr2d-V6-final-dif-ce-focal-schd-agp/WOMEN-Pants-id_00007458-02_1_front --config default_sim_props.yaml --default_body

 using the external pattern, I encounter this issue. Are the design_params.yaml and dataset_properties.yaml files required? I currently only have the specification.json file that meets the format requirements.

Or could you tell me how to generate these two files (design_params.yaml and dataset_properties.yaml) from the specification.json file?

![WeChatbadeefbd71b4c320b913d54c4ee9489a](https://github.com/user-attachments/assets/53f00504-38d0-4681-96fa-281ad522003b)

**Comment by maria-korosteleva** [comment]
You are using the script for dataset (batch) simulation, which requires a `dataset_properties.yaml` file.

You should use the [test_garment_sim.py](https://github.com/maria-korosteleva/GarmentCode/blob/main/test_garment_sim.py) for simulating individual patterns

**Comment by maria-korosteleva** [comment]
What I see on the picture is a boxmesh -- geometry in the initialization stage before simulation. Have the simulation finished? Did you check all the geometry files in the output? Could you share the full output of the script and all the generated files?

**Comment by TanJinxia** [comment]
I’ve reviewed my files, and it appears that the box mesh resembles the final garment exactly. Could it be that the garment has slipped off the body? Do you have any advice on how to fix this issue? Here are all of my output files:
[_predicted_single_241111-00-44-37.zip](https://github.com/user-attachments/files/17706306/_predicted_single_241111-00-44-37.zip)
![WeChat48851d60354cf63127183d1ed5de5d20](https://github.com/user-attachments/assets/58416263-78b6-4790-b8de-8cd5f724dc01)

**Comment by maria-korosteleva** [comment]
Sorry for delay in my replies, but I have reviewed your question, and the issue is quite simple. The pattern and the body are not aligned in the initial state, so the simulation cannot be correctly performed. 

The issue occurs since in [the previous dataset project](https://github.com/maria-korosteleva/Garment-Pattern-Generator) I was using body models, where the center of the body aligns with the world origin, while in GarmentCode all bodies are standing on the y=0 plane with their feet. Consequentially, all the projects using the old dataset produce patterns aligned with center-located bodies. I'd advise to adjust the translation parameter in all the panels of your JSON pattern files to make them higher by half of the height of the body model. In case of default _mean_all_ model we are using that will be 171.99 / 2 = 86

So, doing `panel['translation'][1] += 86` for every panel in all your JSON files should do the trick

P.S. I would not move the body model, because the assumption of the ground plane being at zero is used during simulation in attachment constraint definitions

![image](https://github.com/user-attachments/assets/598aebab-997c-46d6-846b-e152e1561dd9)

**Comment by TanJinxia** [comment]
Thank you for reply!!! It has solved my problem.
