### ISSUE TITLE
Enquiry on the curvature in generated .json file

### ISSUE THREAD

**Issue by Yingqi7777** [maria-korosteleva/GarmentCode#3]
Dear author,

Thanks for your opensourced code. I have a question on visualization of generated sewing pattern file using GarmentViewer. 

In the function `_control_to_abs_coord()` of class `BasicPattern` (in `Garment-Pattern-Generator/packages/pattern.core.py`), the default curvature is Bezier curvature. However, the GarmentCode `GarmentCode/gui.py` could generate various curvature such as `cubic` and `circle`. How to modify the function `_control_to_abs_coord()` to make it performs on other types of curvatures?

Best,
YQ

**Comment by maria-korosteleva** [comment]
Hi YQ!
The code is already adapted to be used with garment viewer for Maya from our previous project. You simply need to set up PYTHONPATH so that it points to GarmentCode implementation of the pattern library :) 
Here the note on this in the docs:
https://github.com/maria-korosteleva/GarmentCode/blob/main/docs/Installation.md#optional-installing-autodesk-mayaqualoth-garment-viewer-gui
