### ISSUE TITLE
strange cloth intersect

### ISSUE THREAD

**Issue by LSQsjtu** [maria-korosteleva/GarmentCode#8]
I face a strange cloth generation when change the arm pose anlge into 80 or others in f_smpl_full_bodied.yaml and keep other parameters.

![Snipaste_2024-05-19_15-36-56](https://github.com/maria-korosteleva/GarmentCode/assets/59142188/8e5445fc-1cfe-454d-a23a-9e07fb1bc452)

But I got a strange intersect render view. It seems be a failure cltoh and can not do simulations.

![Snipaste_2024-05-19_15-31-46](https://github.com/maria-korosteleva/GarmentCode/assets/59142188/1e2f44ab-607c-45ef-9c6d-0223951c5965)

Could you tell me how to change the parameters in the body yaml to get a correct configuration?

**Comment by maria-korosteleva** [comment]
Hi @LSQsjtu! 
As far as I can tell from the screenshot, the intersections are due to an incorrect stitching orientation assignment done by Qualoth simulator during mesh generation.

Briefly, the standard JSON pattern representation that GarmentCode generates represents stitches as edge-edge pairs. This specification lacks information on which vertex of one edge is connected to which of the two vertices of the other edge, creating two options for stitch orientation. Qualoth determines the stitch orientation automatically based on some heuristics (unknown to us). As in your example, these heuristics sometimes fail. 

You can manually correct the stitch orientation by selecting a stitch that looks problematic and tagging the Invert Seam Direction parameter as below: 
<img width="1274" alt="image" src="https://github.com/maria-korosteleva/GarmentCode/assets/6837635/bc8f798c-7388-417e-9f90-25aa4a7da086">


Unfortunately, we do not have access to that part of the pipeline so manual correction is the best I can suggest to you right now 🥲

**Comment by LSQsjtu** [comment]
Thanks for your quick reply. It really helps me.
