### ISSUE TITLE
How to change the pose of the body after rendering?

### ISSUE THREAD

**Issue by Stevada** [maria-korosteleva/GarmentCode#9]
Hi authors,

Thank you for this awesome work! I have rendered the sewing patterns in the GarmentViewe. I want to change the pose of the body to get results like what you put on the repo's main page. Could anyone help me out?

**Comment by maria-korosteleva** [comment]
Hi @Stevada, I'm so very happy you find our project inspiring =) 

Our project focuses on pattern modeling, so most of the post-processing like simulation, rendering, and pose changes is done with a lot of manual support. Here are my suggestions on how to go around posing: 

1) The models for the header you see on the repo main page were created using CLO3D. It gives superior control over the simulation compared to Qualoth (used in our GarmentViewer), allowing to manually get the fabric untangled when the simulation runs imperfectly. It supports loading body animations, and you can load patterns from 3D model UVs or convert GarmentCode SVG files to pdf and load those, see tips [here](https://support.clo3d.com/hc/en-us/community/posts/360023606994-SVG-Import). The caveat is that you need to re-create the panel positioning and stitching manually, since CLO cannot load full pattern information =(

2) Another option is to use our GarmentViewer with Qualoth in combination with Maya tools to animate the body. E.g. SMPL provides a rigged body model and a big dataset of animations mapped to it (AMASS). You could use GarmentViewer to load the pattern on top of a body model in an initial pose and then run the simulation simultaneously with body animation to create a drape in a target pose

In both cases, you would need to have an animated clip for your target body model that starts in the T-Pose/A-pose and smoothly  transitions into the target pose of your choice. 

I hope you find these tips helpful!

**Comment by Stevada** [comment]
Thank you so much with this thorough answer!
